[project]
name = "kio-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "easyocr>=1.7.2",
    "fastapi[standard]>=0.135.2",
    "faster-whisper>=1.0.3",
    "langchain-core>=1.2.28",
    "langchain-ollama>=0.3.0",
    "numpy<2",
    "opencv-python-headless==4.8.1.78",
    "pillow>=12.2.0",
    "python-dotenv>=1.2.2",
]

[tool.fastapi]
app = "main:app"
